# Generated by Django 5.2.2 on 2025-07-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dingdan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jiaoyifangshi",
                    models.CharField(default="未知,出现错误", max_length=2),
                ),
                ("productname", models.CharField(max_length=100)),
                ("productnumber", models.IntegerField(default=0)),
                ("productprice", models.FloatField(default=0.0)),
                ("paymoney", models.FloatField(default=0.0)),
                ("paytime", models.DateTimeField(auto_now_add=True)),
                ("me", models.CharField(max_length=2)),
            ],
        ),
    ]
