# Generated by Django 5.2.2 on 2025-07-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dingdan", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dingdan",
            name="jiaoyifangshi",
        ),
        migrations.RemoveField(
            model_name="dingdan",
            name="me",
        ),
        migrations.AddField(
            model_name="dingdan",
            name="buyer",
            field=models.CharField(default="buyer", max_length=100),
        ),
        migrations.AddField(
            model_name="dingdan",
            name="seller",
            field=models.CharField(default="seller", max_length=100),
        ),
        migrations.AlterField(
            model_name="dingdan",
            name="productname",
            field=models.CharField(default="productname", max_length=100),
        ),
    ]
