# Generated by Django 5.2.2 on 2025-07-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dingdan", "0002_remove_dingdan_jiaoyifangshi_remove_dingdan_me_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dingdan",
            name="paytime",
            field=models.DateTimeField(),
        ),
    ]
