# Generated by Django 5.2.2 on 2025-07-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dingdan", "0003_alter_dingdan_paytime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dingdan",
            name="paytime",
            field=models.CharField(default="2025-07-05 18:30:11.551219"),
        ),
    ]
