# Generated by Django 5.2.2 on 2025-07-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dingdan", "0004_alter_dingdan_paytime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dingdan",
            name="paytime",
            field=models.CharField(default="2025-07-06 20:40:43.084289"),
        ),
    ]
