# Generated by Django 5.2.2 on 2025-07-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="huowu",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="money",
            field=models.FloatField(default=100.0),
        ),
    ]
