# Generated by Django 5.2.2 on 2025-07-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0002_useraccount_huowu_useraccount_money"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="appname",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
