# Generated by Django 5.2.2 on 2025-07-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0003_useraccount_appname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="appname",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
