# Generated by Django 5.2.2 on 2025-07-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0004_alter_useraccount_appname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraccount",
            old_name="huowu",
            new_name="huowunumber",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="huowudescription",
            field=models.CharField(blank=True, default="null", null=True),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="huowuimgurl",
            field=models.URLField(blank=True, default="null", null=True),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="huowuname",
            field=models.CharField(blank=True, default="null", null=True),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="huowuprice",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
