# Generated by Django 5.2.2 on 2025-07-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0005_rename_huowu_useraccount_huowunumber_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="huowudescription",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="huowuimgurl",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="huowuname",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="huowunumber",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="huowuprice",
        ),
    ]
