# Generated by Django 5.2.2 on 2025-07-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buying", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="number",
            field=models.FloatField(blank=True, default=1000.0, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="price",
            field=models.FloatField(blank=True, default=10.0, null=True),
        ),
    ]
