# Generated by Django 5.2.2 on 2025-07-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buying", "0002_products_number_products_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="buyname",
            field=models.CharField(
                blank=True, default="null", max_length=100, null=True
            ),
        ),
    ]
