# Generated by Django 5.2.2 on 2025-07-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buying", "0003_products_buyname"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="username",
            field=models.CharField(default="user", max_length=100),
        ),
    ]
