# Generated by Django 5.2.2 on 2025-07-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Index",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=2000)),
                (
                    "img_url",
                    models.URLField(
                        blank=True,
                        default="https://ts3.tc.mm.bing.net/th/id/OIP-C.ThRuhUBIyjg4RPQLDYBN2AHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
                        max_length=2000,
                    ),
                ),
            ],
        ),
    ]
