# Generated by Django 5.2.2 on 2025-07-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sellproduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="null", max_length=100, null=True
                    ),
                ),
                ("price", models.FloatField(default=0.0)),
                (
                    "img_url",
                    models.URLField(
                        blank=True, default="null", max_length=2000, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="null", max_length=200, null=True
                    ),
                ),
                ("number", models.FloatField(default=0.0)),
            ],
        ),
    ]
