# Generated by Django 5.2.2 on 2025-07-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selling", "0002_sellproduct_appname"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellproduct",
            name="username",
            field=models.CharField(default="user", max_length=100),
        ),
    ]
